# Team name / identifier.
name = "example"

# Specifies all team members by name.
[[members]]
# Specifies members full name.
name = ""
# Specifies the members roles ['skipper', 'trimmer', 'bowman']
roles = [""]