# Design holds information about the ships design characteristics
[design]
# Mode specifies the type of the hull design/mode [displace; semi; planing; hydrofoil;]
mode = ""
# Stabilization specifies the method used to stabilize the ship [foils; centreboard; daggerboard; keel;]
stabilization = ""
# Hull specifies the hull type [mono; multi;]
hull = ""

# Composition specifies how the ships weight is composed.
[composition]
keel_percentage = 10 # specifies the weight percentage of the keel
cfk_percentage = 30 # specifies the weight percentage of carbon fibre reinforced polymer
gfk_percentage = 40 # specifies the weight percentage of fibreglass reinforced plastic
wood_percentage = 20 # specifies the weight percentage of wood