# Design holds information about the ships design characteristics
[design]
# Mode specifies the type of the hull design/mode [displace; semi; planing; hydrofoil;]
mode = ""
# Stabilization specifies the method used to stabilize the ship [foils; centreboard; daggerboard; keel;]
stabilization = ""
# Hull specifies the hull type [mono; multi;]
hull = ""

# Composition specifies how the ships weight is composed. 
# Weight not listed here is counted as "default" material, which means material that gets no additional bonus (e.g. sails).
[composition]
keel_percentage = 20 # specifies the weight percentage of the keel
cfk_percentage = 5 # specifies the weight percentage of carbon fibre reinforced polymer
alu_percentage = 5 # specifies the weight percentage of aluminium
gfk_percentage = 68 # specifies the weight percentage of fibreglass reinforced plastic
wood_percentage = 0 # specifies the weight percentage of wood