# Friendly name (e.g. AETHER)
name = "Example"
# Boat class (e.g. DEHLER 30 OD)
class = "Example Class 00"
# Boat age (specify the vessel's construction year)
age = "2024"
# Name of the manufacturer of the boat (e.g. DEHLER)
builder = "Example"
# Name of the designer of the boat (e.g. JUDEL/VROELIJK)
designer = "Example"