[dimension]
# LOA specifies the length in meters from the foremost to the rearmost point of the ship.
length_over_all = 5.51
# Draft specifies the vertical distance from the bottom of the keel to the waterline in meters.
draft = 0.71
# Beam specifies the largest width of the beam in meters.
beam = 2.6
# Forestay height (IMSL) specifies the vertical height of the forestay in meters.
forestay_height = 8.5
# Wetted surface area (WSS) specifies the surface area touching the water in square meters.
wetted_surface_area = 3
# Specifies the displacement while sailing in kg.
sailing_displacement = 180
# Specifies the maximum crew weight in kg.
max_crew_weight = 240

[sail_area]
# Specifies the area of the main sail in square meters.
main = 17
# Specifies the area of the largest onboard jib sail in square meters.
jib = 4.15
# Specifies the area of the largest onboard downwind sail (e.g. gennaker or code zero) in square meters.
asymmetric_spinnaker = 0
# Specifies the area of the largest onboard downwind sail (e.g. spinnaker) in square meters.
symmetric_spinnaker = 21