# Design holds information about the ships design characteristics
[design]
# Mode specifies the type of the hull design/mode [displace; semi; planing; hydrofoil;]
mode = "displace"
# Stabilization specifies the method used to stabilize the ship [foils; centreboard; daggerboard; finkeel; bulbkeel; fullkeel;]
stabilization = "finkeel"
# Hull specifies the hull type [mono; multi;]
hull = "mono"

# Composition specifies how the ships weight is composed.
[composition]
ballast_percentage = 35
alu_percentage = 3
gfk_percentage = 40
wood_percentage = 2
engine_percentage = 3
amenity_percentage = 15