# Friendly name (e.g. AETHER)
name = "Example GC32"
# Boat class (e.g. DEHLER 30 OD)
class = "GC32"
# Boat age (specify the vessel's construction year)
age = "2012"
# Name of the manufacturer of the boat (e.g. DEHLER)
builder = "Premier Composite Technologies"
# Name of the designer of the boat (e.g. JUDEL/VROELIJK)
designer = "Dr Martin Fischer"