name: Validate and tag application pull request
on: [pull_request]

jobs:
  validate-and-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    permissions:
      pull-request: write
    steps:
      - name: label pull request
        uses: actions/labeler@v5
        with:
          configuration-path: ".github/labeler.yml"
