name: Tag application pull request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: label pull request
        uses: actions/labeler@v5
        with:
          configuration-path: ".github/labeler.yml"
