name: Validate register request
on: 
  pull_request:
    paths:
      - "register/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: install ci engine
        run: |
          go install github.com/megakuul/opensail/engine@latest
          engine --version

      - name: validate request
        run: |
          engine validate --input-path "." \
            --github-owner ${{ github.repository_owner }} \
            --github-repo ${{ github.event.repository.name }} \
            --github-pr-number ${{ github.event.pull_request.number }} \
            --github-token ${{ secrets.GITHUB_TOKEN }}